### PR TITLE
fix: resolve the right config file and args from cli

### LINKED ISSUE #6: bumpp.config.ts
### Describe the bug

你好，我现在正在研究这个包的用法，但是我发现配置了bumpp.config.ts配置并不生效，然后我看了下源代码
image
是不是name参数配置有误

### Reproduction

  const { config } = await loadConfig<VersionBumpOptions>({     name: 'bump',     defaults: bumpConfigDefaults,     overrides: {       ...(overrides as VersionBumpOptions),     },     cwd,   })

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 481.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #13: After upgrade to v9.2.0 bump.config.ts not work
### Describe the bug

After upgrade to v9.2.0 bump.config.ts not work, but with v9.1.0 it works.

### Reproduction

https://github.com/yunsii/unplugin-polish-tagged-templates

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 11.55 GB / 15.52 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    pnpm: 8.6.9 - ~/.local/share/pnpm/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Bernankez**
### Description

This PR contains two fixes.
The first is that the [document here](https://github.com/antfu/bumpp/blob/bf20fc75105282b5570261c3ab1069ad467b3c37/README.md?plain=1#L17) says that the config name is `bumpp.config.ts`, but the name is actually [`bump.config.ts`](https://github.com/antfu/bumpp/blob/bf20fc75105282b5570261c3ab1069ad467b3c37/src/config.ts#L20). Maybe it's better to support both of the names? This will fix #6.
And because of adding the `--no-commit` and `--no-tag` options in `v9.2.0`, this will set the `commit` and `tag` from cli args to `true` instead of `undefined` according to https://github.com/cacjs/cac#negated-options. And this will overrides the config from config file. I made some fixes so it can now read the right args from cli. This will fix #13 and #19.

### Linked Issues

#6 #13 #19

### CODE REVIEW

**Comment by DrJume** [comment]
LGTM

File: src/config.ts [hunk 1]
```diff
@@ -16,8 +17,10 @@ export const bumpConfigDefaults: VersionBumpOptions = {
 
 export async function loadBumpConfig(overrides?: Partial<VersionBumpOptions>,
   cwd = process.cwd()) {
+  const childrenNames = readdirSync(cwd)
+  const name = childrenNames.some(name => name.includes('bumpp')) ? 'bumpp' : 'bump'
   const { config } = await loadConfig<VersionBumpOptions>({
-    name: 'bump',
+    name,
```
Comment (antfu) [inline src/config.ts:23]: I don't think this is a good idea to rely on readdirSync, as the config can come from different sources. Instead we could run c12 twice and merge the config.

Comment (Bernankez) [reply src/config.ts:23]: Yes, I missed that point.

File: src/config.ts [hunk 2]
```diff
@@ -18,11 +18,18 @@ export async function loadBumpConfig(
   overrides?: Partial<VersionBumpOptions>,
   cwd = process.cwd(),
 ) {
+  const { config: bumppConfig } = await loadConfig<VersionBumpOptions>({
+    name: 'bumpp',
```
Comment (antfu) [inline src/config.ts:22]: After a second thought, I think it's better to only read from `bump` to avoid confusion,  as we already fix the docs for quite a while now.

Comment (Bernankez) [reply src/config.ts:22]: Thanks, LGTM
